CREATE TABLE public.DOMAIN
(
    ID                   UUID         NOT NULL PRIMARY KEY,
    DOMAIN_ID            UUID         NOT NULL,
    TENANT               VARCHAR(255) NOT NULL,
    NAME                 VARCHAR(255) NOT NULL,
    LABEL                VARCHAR(255) NOT NULL,
    ICON                 VARCHAR(255) NOT NULL,
    COLUMN_CONFIGURATION JSON         NOT NULL,
    CREATE_DATE          TIMESTAMP,
    CHANGE_DATE          TIMESTAMP
);

CREATE TABLE public.COLUMN_CONFIGURATION
(
    ID           UUID         NOT NULL PRIMARY KEY,
    DOMAIN_ID    UUID         NOT NULL,
    ACCESSOR_KEY VARCHAR(255) NOT NULL,
    HEADER       VARCHAR(255) NOT NULL,
    CREATE_DATE  TIMESTAMP,
    CHANGE_DATE  TIMESTAMP,
    UNIQUE (ID, DOMAIN_ID),
    FOREIGN KEY (DOMAIN_ID) REFERENCES DOMAIN (id)
);

CREATE TABLE public.ENTRY
(
    ID          UUID NOT NULL PRIMARY KEY,
    DOMAIN_ID   UUID NOT NULL,
    DATA        JSON NOT NULL,
    CREATE_DATE TIMESTAMP,
    CHANGE_DATE TIMESTAMP,
    FOREIGN KEY (DOMAIN_ID) REFERENCES DOMAIN (id)
);